##############################################
# Part common to the frontend and the agents #
##############################################

# Location of the task directory
tasks_directory: ./tasks

# Aliases for containers
# Only containers listed here can be used by tasks
containers:
    default: ingi/inginious-c-default
    sekexe: ingi/inginious-c-sekexe

##############################################
#       Part used only by the frontend       #
##############################################

# Backend
# Can be "local" (run containers on the same machine)
# Or "remote" (connect to distant and manually installed agents. This includes boot2docker)
backend: local

# List of the agents to which the backend will try
# to connect (backend: remote only) (the default config below is the one for boot2docker on OS X)
#agents:
#  - host: "192.168.59.103"
#    port: 5001

# MongoDB options
mongo_opt:
    host: localhost
    database: INGInious

# Plugins that will be loaded by the frontend
plugins:
  - plugin_module: frontend.plugins.auth.demo_auth
    users:
        # register the user "test" with the password "test"
        test: test

# Allow HTML in tasks? can be true, false or "tidy" (to run HTMLTidy)
allow_html: tidy

##############################################
#        Part used only by the agents        #
##############################################

# Tmp folder used by the agent
local_agent_tmp_dir: "/tmp/inginious_agent"

# Port on which the local agent will listen (only for backend:remote)
#local_agent_port: 5001
