##############################################
# Part common to the frontend and the agents #
##############################################

# Location of the task directory
tasks_directory: ./tasks

# Aliases for containers
# Only containers listed here can be used by tasks
containers:
    default: ingi/inginious-c-default
    sekexe: ingi/inginious-c-sekexe

##############################################
#        Part used only by the agents        #
##############################################

# Port on which the local agent will listen
local_agent_port: 5001

# Tmp folder used by the agent
local_agent_tmp_dir: "/tmp/inginious_agent"

##############################################
#       Part used only by the frontend       #
##############################################

# List of the agents to which the backend will try
# to connect
agents:
  - host: "192.168.59.103"
    port: 5001

# MongoDB options
mongo_opt:
    host: localhost
    database: INGInious

# Plugins that will be loaded by the frontend
plugins:
  - plugin_module: frontend.plugins.git_repo
    repo_directory: ./repo_submissions
  - plugin_module: frontend.plugins.auth.demo_auth
    users:
        test: test

# Allow HTML in tasks? can be true, false or "tidy" (to run HTMLTidy)
allow_html: tidy