# Backend
# Can be:
# - "local" (run containers on the same machine)
# - "remote" (connect to distant docker daemon and auto start agents) (choose this if you use boot2docker)
# - "remote_manual" (connect to distant and manually installed agents)
backend: remote

# List of remote docker daemon to which the backend will try
# to connect (backend: remote only) (the default config below is the one for boot2docker on OS X)
docker_daemons:

  - remote_host: "192.168.59.103" ##host of the docker daemon *from the frontend*
    remote_docker_port: 2375 ##port of the distant docker daemon *from the frontend*
    remote_agent_port: 63456 ##A mandatory port used by the backend and the agent that will be automatically started. Needs to be available on the
                             ##remote host, and to be open in the firewall.
    ##does the remote docker requires tls? Defaults to false
    ##parameter can be set to true or path to the certificates
    #use_tls: false
    ##link to the docker daemon *from the host that runs the docker daemon*. Defaults to:
    #local_location: "unix:///var/run/docker.sock"
    ##path to the cgroups "mount" *from the host that runs the docker daemon*. Defaults to:
    #cgroups_location: "/sys/fs/cgroup"

# List of remote agents to which the backend will try
# to connect (backend: remote_manual only) (the default config below is the one for boot2docker on OS X)
#agents:
#  - host: "192.168.59.103"
#    port: 5001

# MongoDB options
mongo_opt:
    host: localhost
    database: INGInious

# Location of the task directory
tasks_directory: ./tasks

# Aliases for containers
# Only containers listed here can be used by tasks
containers:
    default: ingi/inginious-c-default
    sekexe: ingi/inginious-c-sekexe

# Plugins that will be loaded by the frontend
plugins:
  - plugin_module: frontend.plugins.auth.demo_auth
    users:
        # register the user "test" with the password "test"
        test: test

# Allow HTML in tasks? can be true, false or "tidy" (to run HTMLTidy)
allow_html: tidy

# Disable INGInious?
maintenance: false