tasks_directory: ./tasks
containers:
    default: ingi/inginious-c-default
    sekexe: ingi/inginious-c-sekexe
docker_instances:
  - server_url: "tcp://192.168.59.103:2375"
callback_managers_threads: 2
submitters_processes: 2
mongo_opt:
    host: localhost
    database: INGInious
plugins:
  - plugin_module: frontend.plugins.git_repo
    repo_directory: ./repo_submissions
  - plugin_module: frontend.plugins.auth.demo_auth
    users:
        test: test
allow_html: tidy